EWG.Frontend/ViewModels/SessionViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace EWG.Frontend.ViewModels
{
    public class SessionViewModel
    {
        [Required]
        public string Email { get; set; }
        [Required]
        public string Password { get; set; }
        public string ReturnUrl { get; set; }
    }
}

EWG.Frontend/Controllers/SessionController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using EWG.Domain.Entities.Security;
using EWG.Frontend.Security;
using EWG.Frontend.ViewModels;
using EWG.Infrastructure.Dal;

namespace EWG.Frontend.Controllers
{
    public class SessionController : Controller
    {
        private readonly IAuthenticator _authenticator;
        private readonly ICrudRepository<IdentityUser> _repository;
        private const string errorMessage = "Invalid username or password";

        public SessionController(IAuthenticator authenticator, ICrudRepository<IdentityUser> repository)
        {
            _authenticator = authenticator;
            _repository = repository;
        }

        [HttpGet]
        public ActionResult New(string returnUrl)
        {
            return View(new SessionViewModel { ReturnUrl = returnUrl });
        }

        [HttpPost]
        public JsonResult Create(SessionViewModel sessionViewModel)
        {
            IdentityUser user = null;
            if (ModelState.IsValid)
            {
                user = _repository.Get().FirstOrDefault(x => x.Email == sessionViewModel.Email);
                if (user == null)
                {
                    ModelState.AddModelError(string.Empty, errorMessage);
                }
            }

            if (ModelState.IsValid)
            {
                if (!BCrypt.Net.BCrypt.Verify(sessionViewModel.Password, user.HashedPassword))
                {
                    ModelState.AddModelError(string.Empty, errorMessage);
                }
            }

            if (ModelState.IsValid)
            {
                _authenticator.SetCookie(user.Email, user.Username);
                var returnUrl = sessionViewModel.ReturnUrl;
                if (returnUrl != null)
                {
                    Uri returnUri;
                    if (Uri.TryCreate(returnUrl, UriKind.Relative, out returnUri))
                    {
                        return Json(new {success = true});
                    }
                }

                return Json(new { success = true });
            }

            return Json(new { success = false });
        }

        public JsonResult IsAuthenticated()
        {
            var identityName = HttpContext.User.Identity.Name;

            if (!string.IsNullOrEmpty(identityName))
            {
                var identity = _repository.Get().First(x => x.Email == identityName);
                return Json(new { success = true, username = identity.Username }, JsonRequestBehavior.AllowGet);
            }

            return Json(new {success = false}, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpPost]
        public JsonResult Destroy()
        {
            _authenticator.SignOut();
            Session.Abandon();
            return Json(new {success = true}, JsonRequestBehavior.AllowGet);
        }
    }
}

EWG.Frontend/Views/Session/New.cshtml
@model EWG.Frontend.ViewModels.SessionViewModel

@{
    Layout = "~/Views/Shared/_LayoutBase.cshtml";
}

<div class="container" style="height: 100%;">
    @using (Html.BeginForm("Create", "Session", FormMethod.Post, new {@class = "form-signin"}))
    {
        <div class="form-group">
            @Html.LabelFor(x => x.Email)
            @Html.TextBoxFor(x => x.Email, new {@class = "form-control", placeholder = "E-mail"})
            @Html.ValidationMessageFor(x => x.Email)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.Password)
            @Html.PasswordFor(x => x.Password, new {@class = "form-control", placeholder = "Password"})
            @Html.ValidationMessageFor(x => x.Password)
        </div>

        @Html.ValidationSummary(true)

        <div>
            <button type="submit" class="btn btn-primary btn-block">Log In</button>
        </div>

        @Html.Hidden("ReturnUrl", Model.ReturnUrl)
    }
</div>